/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operacionespooivan;

/**
 *
 * @author 52449
 */
public class operaciones extends javax.swing.JFrame {

    /**
     * Creates new form operaciones
     */
    public operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txtnum1 = new javax.swing.JTextField();
        Txtnum2 = new javax.swing.JTextField();
        Btnexit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Btndivi = new javax.swing.JButton();
        Btnmulti = new javax.swing.JButton();
        Btnresta = new javax.swing.JButton();
        Btnsuma = new javax.swing.JButton();
        Lbigual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btnexit.setText("me voy");
        Btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnexitActionPerformed(evt);
            }
        });

        jButton2.setText("borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Btndivi.setText("/");
        Btndivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndiviActionPerformed(evt);
            }
        });

        Btnmulti.setText("*");
        Btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmultiActionPerformed(evt);
            }
        });

        Btnresta.setText("-");
        Btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnrestaActionPerformed(evt);
            }
        });

        Btnsuma.setText("+");
        Btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsumaActionPerformed(evt);
            }
        });

        Lbigual.setText("resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbigual, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btnexit)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(Txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btnsuma)
                            .addComponent(Btnmulti)
                            .addComponent(Btndivi)
                            .addComponent(Btnresta)))
                    .addComponent(Txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnsuma))
                .addGap(16, 16, 16)
                .addComponent(Btnresta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbigual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btnmulti)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnexit)
                    .addComponent(jButton2)
                    .addComponent(Btndivi))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsumaActionPerformed
       double n1,n2,suma;
       n1=Double.parseDouble(Txtnum1.getText());
       n2=Double.parseDouble(Txtnum2.getText());
       suma=n1+n2;
       Lbigual.setText(String.valueOf(suma));
       
    }//GEN-LAST:event_BtnsumaActionPerformed

    private void BtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnrestaActionPerformed
        double n1,n2,res;
       n1=Double.parseDouble(Txtnum1.getText());
       n2=Double.parseDouble(Txtnum2.getText());
       res=n1-n2;
       Lbigual.setText(String.valueOf(res));
    }//GEN-LAST:event_BtnrestaActionPerformed

    private void BtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmultiActionPerformed
        double n1,n2,multi;
       n1=Double.parseDouble(Txtnum1.getText());
       n2=Double.parseDouble(Txtnum2.getText());
       multi=n1*n2;
       Lbigual.setText(String.valueOf(multi));
    }//GEN-LAST:event_BtnmultiActionPerformed

    private void BtndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndiviActionPerformed
        double n1,n2,div;
       n1=Double.parseDouble(Txtnum1.getText());
       n2=Double.parseDouble(Txtnum2.getText());
       div=n1/n2;
       Lbigual.setText(String.valueOf(div));
    }//GEN-LAST:event_BtndiviActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Txtnum1.setText(null);
        Txtnum2.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btndivi;
    private javax.swing.JButton Btnexit;
    private javax.swing.JButton Btnmulti;
    private javax.swing.JButton Btnresta;
    private javax.swing.JButton Btnsuma;
    private javax.swing.JLabel Lbigual;
    private javax.swing.JTextField Txtnum1;
    private javax.swing.JTextField Txtnum2;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
