/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package preciostoglebutons;

/**
 *
 * @author 52449
 */
public class precios extends javax.swing.JFrame {

    /**
     * Creates new form precios
     */
    public precios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtPrecioBase = new javax.swing.JTextField();
        BtnCal = new javax.swing.JButton();
        etiTotal = new javax.swing.JLabel();
        TbtnIstalacion = new javax.swing.JToggleButton();
        TbtnFormacion = new javax.swing.JToggleButton();
        TbtnAlimentacionBD = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        etiIsta = new javax.swing.JLabel();
        etiAli = new javax.swing.JLabel();
        etiFor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCal.setText("calcular");
        BtnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalActionPerformed(evt);
            }
        });

        etiTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiTotal.setBorder(new javax.swing.border.MatteBorder(null));

        TbtnIstalacion.setText("istalacion");

        TbtnFormacion.setText("formacion");

        TbtnAlimentacionBD.setText("AlimBD");

        jLabel3.setText("precio base");

        etiIsta.setText("40");

        etiAli.setText("200");

        etiFor.setText("200");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TbtnFormacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiFor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TbtnIstalacion)
                        .addGap(45, 45, 45)
                        .addComponent(etiIsta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TbtnAlimentacionBD)
                        .addGap(18, 18, 18)
                        .addComponent(etiAli, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(TxtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TbtnIstalacion)
                    .addComponent(etiIsta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TbtnAlimentacionBD)
                    .addComponent(etiAli))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TbtnFormacion)
                    .addComponent(etiFor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCal))
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalActionPerformed
        double precio_base;
double precio_instal=0; 
double precio_for=0; 
double precio_ali=0; 
 

 
precio_base = Double.parseDouble(TxtPrecioBase.getText());
precio_instal = Double.parseDouble(etiIsta.getText());
precio_for = Double.parseDouble(etiFor.getText());
precio_ali = Double.parseDouble(etiAli.getText());


 
double precio_total;
 
precio_total = precio_base;
 
if (TbtnIstalacion.isSelected()) { 
 precio_total = precio_total+precio_instal;
}
 
if (TbtnAlimentacionBD.isSelected()) { 
 precio_total = precio_total+precio_for; 
}
 
if (TbtnFormacion.isSelected()) {
 precio_total = precio_total+precio_ali;
}
 
 etiTotal.setText(precio_total+" €");

    }//GEN-LAST:event_BtnCalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new precios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCal;
    private javax.swing.JToggleButton TbtnAlimentacionBD;
    private javax.swing.JToggleButton TbtnFormacion;
    private javax.swing.JToggleButton TbtnIstalacion;
    private javax.swing.JTextField TxtPrecioBase;
    private javax.swing.JLabel etiAli;
    private javax.swing.JLabel etiFor;
    private javax.swing.JLabel etiIsta;
    private javax.swing.JLabel etiTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
