/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial.pkg1.picazo;

import javax.swing.JOptionPane;

/**
 *
 * @author 52449
 */
public class cuadradoss extends javax.swing.JInternalFrame {
    private Object txtValor;
    private Object resultado;

    /**
     * Creates new form cuadradoss
     */
    public cuadradoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txtnumero = new javax.swing.JTextField();
        BtnAceptar = new javax.swing.JButton();
        Btnclean = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        Txtresult = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 48)); // NOI18N
        jLabel1.setText("cuadrado");

        jLabel2.setText("numero");

        Txtnumero.setText(" ");
        Txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnumeroActionPerformed(evt);
            }
        });

        BtnAceptar.setText("Aceptar");
        BtnAceptar.setToolTipText("boton de resultado");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        Btnclean.setText("Nuevo");
        Btnclean.setToolTipText("borrar");
        Btnclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncleanActionPerformed(evt);
            }
        });

        BtnExit.setText("Salir");
        BtnExit.setToolTipText("abandonar");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        Txtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtresultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtresult, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BtnAceptar)
                        .addGap(151, 151, 151)
                        .addComponent(BtnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Btnclean)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txtresult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btnclean)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnExit))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnumeroActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
     
        int num,resultado;
        num=Integer.parseInt(Txtnumero.getText());
        resultado=num*num;
        JOptionPane.showMessageDialog(null,resultado,"CUADRADO DE UN NUMERO",JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtncleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncleanActionPerformed
    Txtnumero.setText(null) ;// TODO add your handling code here:
    }//GEN-LAST:event_BtncleanActionPerformed

    private void TxtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtresultActionPerformed
       
      
    }//GEN-LAST:event_TxtresultActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_BtnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton Btnclean;
    private javax.swing.JTextField Txtnumero;
    private javax.swing.JTextField Txtresult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
