/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colorespoopicazo;

/**
 *
 * @author 52449
 */
public class colors extends javax.swing.JFrame {

    /**
     * Creates new form colors
     */
    public colors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Lbcolor = new javax.swing.JLabel();
        Btnacept = new javax.swing.JButton();
        Btnexit = new javax.swing.JButton();
        OptRojo = new javax.swing.JRadioButton();
        OptVerde = new javax.swing.JRadioButton();
        OptAzul = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        Lbcolor.setText("color");

        Btnacept.setBackground(new java.awt.Color(204, 255, 204));
        Btnacept.setText("aceptar");
        Btnacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaceptActionPerformed(evt);
            }
        });

        Btnexit.setBackground(new java.awt.Color(204, 255, 204));
        Btnexit.setText("exitt");
        Btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnexitActionPerformed(evt);
            }
        });

        OptRojo.setBackground(new java.awt.Color(204, 255, 204));
        buttongrup.add(OptRojo);
        OptRojo.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        OptRojo.setText("rojo");
        OptRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptRojoActionPerformed(evt);
            }
        });

        OptVerde.setBackground(new java.awt.Color(204, 255, 204));
        buttongrup.add(OptVerde);
        OptVerde.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        OptVerde.setText("verde");
        OptVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptVerdeActionPerformed(evt);
            }
        });

        OptAzul.setBackground(new java.awt.Color(204, 255, 204));
        buttongrup.add(OptAzul);
        OptAzul.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        OptAzul.setText("azul");
        OptAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptAzulActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("COLORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnacept)
                                .addGap(32, 32, 32)
                                .addComponent(Btnexit)))
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OptVerde)
                            .addComponent(OptAzul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OptRojo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(OptRojo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OptAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbcolor)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnacept)
                    .addComponent(Btnexit))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnexitActionPerformed

    private void OptRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptRojoActionPerformed
        OptRojo.setSelected(true);
    }//GEN-LAST:event_OptRojoActionPerformed

    private void OptVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptVerdeActionPerformed
       OptVerde.setSelected(true);
    }//GEN-LAST:event_OptVerdeActionPerformed
  
    private void OptAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptAzulActionPerformed
        OptAzul.setSelected(true);
    }//GEN-LAST:event_OptAzulActionPerformed

    private void BtnaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaceptActionPerformed
        String mensage="color elegido:";
        if(OptRojo.isSelected()){
            mensage=mensage+"rojo";
        }
        else
        if(OptVerde.isSelected()){
            mensage=mensage+"verde";
        }
        else
        if(OptAzul.isSelected()){
            mensage=mensage+"azul";
        }
        Lbcolor.setText(mensage);
    }//GEN-LAST:event_BtnaceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnacept;
    private javax.swing.JButton Btnexit;
    private javax.swing.JLabel Lbcolor;
    private javax.swing.JRadioButton OptAzul;
    private javax.swing.JRadioButton OptRojo;
    private javax.swing.JRadioButton OptVerde;
    private javax.swing.ButtonGroup buttongrup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
